### ISSUE TITLE
PlayerNotConnected problem

### ISSUE THREAD

**Issue by xXenvy** [ooliver1/mafic#65]
### Summary

When the bot is playing some music on a channel and at that time the bot is restarted the bot still plays music but when you use player.stop() it throws an error `mafic.errors.PlayerNotConnected: The player is not connected to a voice channel,` even though it is on the channel and playing music. In most cases when it throws an error you can just execute player.stop() again and everything works normally

### Reproduction Steps

- Run some song in the bot
- Restart the bot
- When the bot won't stop playing music (sometimes it stops) try executing player.stop()

### Minimal Reproducible Code

```Python
Ignoring exception in command <nextcord.application_command.SlashApplicationSubcommand object at 0x00000155F9F11EA0>:
Traceback (most recent call last):
  File "C:\Users\szymo\PycharmProjects\SmiffyBot\venv\lib\site-packages\nextcord\application_command.py", line 890, in invoke_callback_with_hooks
    await self(interaction, *args, **kwargs)
  File "C:\Users\szymo\PycharmProjects\SmiffyBot\Commands\music\CommandStop.py", line 48, in music_stop
    await player.stop()
  File "C:\Users\szymo\PycharmProjects\SmiffyBot\venv\lib\site-packages\mafic\player.py", line 648, in stop
    await self.update(track=None, replace=True)
  File "C:\Users\szymo\PycharmProjects\SmiffyBot\venv\lib\site-packages\mafic\player.py", line 530, in update
    raise PlayerNotConnected
mafic.errors.PlayerNotConnected: The player is not connected to a voice channel.
```

### Expected Results

When restarting the bot, the bot would exit the channel and stop playing the song

### Actual Results

Bugs the bot, you can't stop the song after restarting the bot. (Actually it can, but you have to execute player.stop() 2 times)

### Lavalink Information

Version:        3.7.5
Build time:     06.03.2023 12:02:05 UTC
Branch          HEAD
Commit:         c00286d
Commit time:    06.03.2023 11:59:46 UTC
JVM:            17.0.6
Lavaplayer      1.4.0-original

### System Information

- Python v3.10.6-final
- mafic v2.0.1
- aiohttp v3.8.1
- nextcord v2.4.0-final
- system info: Linux 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

So far I have found a solution but sometimes it requires typing the stop command 2 times
```py
try:
    player.loop = False
    await player.set_volume(100)
    await player.stop()
except errors.PlayerNotConnected:
    embed = Embed(
        title="<:error:919648598713573417> Wystąpił błąd.",
        color=Color.red(),
        timestamp=utils.utcnow(),
        description=f"**Use command again.**"
            )
        embed.set_author(name=interaction.user, icon_url=self.avatars.get_user_avatar(interaction.user))
        return await interaction.followup.send(embed=embed)
```

**Comment by Qadronic** [comment]
I think that this is a bug in nextcord working (sorry, I mean nextcord working in mafic library), because while I'm using the disnake library, everything is fine (bot leaves the channel when the script shuts down)
