### ISSUE TITLE
nextcord.errors.ApplicationInvokeError: Command raised an exception: IndexError: list index out of range

### ISSUE THREAD

**Issue by DevSimpler** [ooliver1/mafic#84]
### Summary

look

### Reproduction Steps

```python
@bot.slash_command(dm_permission=False)
async def play(inter: nextcord.Interaction, query: str):
    if not inter.guild.voice_client:
        player = await inter.user.voice.channel.connect(cls=mafic.Player)
    else:
        player = inter.guild.voice_client

    tracks = await player.fetch_tracks(query)

    if not tracks:
        return await inter.send("No tracks found.")

    track = tracks[0]

    await player.play(track)

    await inter.send(f"Playing {track.title}.")
```

### Minimal Reproducible Code

```Python
tracks = await player.fetch_tracks(query)

    if not tracks:
        return await inter.send("No tracks found.")

    track = tracks[0]

    await player.play(track)
```

### Expected Results

to play music

### Actual Results

it gave me a error

### Lavalink Information

Version: 3.7.5
Build time: 06.03.2023 12:02:05 UTC
Branch HEAD
Commit: c00286d
Commit time: 06.03.2023 11:59:46 UTC
JVM: 17.0.6
Lavaplayer 1.4.0-original

### System Information

- Python v3.10.11-final
- mafic v2.4.2
- aiohttp v3.8.3
- nextcord v2.4.0-final
- system info: Windows 10 10.0.22621

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

nope

**Comment by ooliver1** [comment]
> I have shown the entire traceback, if possible.
You have not provided the traceback.

**Comment by DevSimpler** [comment]
wtf is a traceback
